# Generated by Django 2.0.4 on 2018-05-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=255)),
                ('deferimento', models.DateField()),
                ('presidente_nacional', models.CharField(max_length=255)),
                ('legenda', models.PositiveIntegerField()),
            ],
        ),
    ]
