# Generated by Django 2.0.4 on 2018-05-04 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('politicos', '0002_auto_20180504_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_camara', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('id_legislatura', models.IntegerField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='politicos.Partido')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.Estado')),
            ],
        ),
    ]
