# Generated by Django 2.0.4 on 2018-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicos', '0003_deputado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='deferimento',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='legenda',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='presidente_nacional',
        ),
        migrations.AddField(
            model_name='partido',
            name='id_camara',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
