# Generated by Django 2.0.4 on 2018-05-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_uf'),
        ('politicos', '0004_auto_20180504_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoCotaParlamentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legislatura', models.IntegerField(null=True)),
                ('data_emissao', models.DateTimeField(null=True)),
                ('id_documento', models.IntegerField(null=True)),
                ('tipo_documento', models.IntegerField(choices=[(0, 'Nota Fiscal'), (1, 'Recibo'), (2, 'Despesa no Exterior')], null=True)),
                ('ano', models.IntegerField(null=True)),
                ('especificacao_subcota', models.IntegerField(null=True)),
                ('lote', models.IntegerField(null=True)),
                ('mes', models.IntegerField(null=True)),
                ('parcela', models.IntegerField(null=True)),
                ('ressarcimento', models.IntegerField(null=True)),
                ('subcota', models.IntegerField(null=True)),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('descricao', models.CharField(max_length=127, null=True)),
                ('descricao_especificacao', models.CharField(max_length=31, null=True)),
                ('fornecedor', models.CharField(max_length=255, null=True)),
                ('numero_documento', models.CharField(max_length=63, null=True)),
                ('nome_passageiro', models.CharField(max_length=63, null=True)),
                ('trecho_viagem', models.CharField(max_length=127, null=True)),
                ('valor_documento', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('valor_glosa', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('valor_restituicao', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
            options={
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.AddField(
            model_name='deputado',
            name='carteira_parlamentar',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='gastocotaparlamentar',
            name='deputado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='politicos.Deputado'),
        ),
        migrations.AddField(
            model_name='gastocotaparlamentar',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_deputados', to='empresas.Empresa'),
        ),
    ]
