# Generated by Django 2.0.4 on 2018-05-08 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('politicos', '0005_auto_20180508_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deputado',
            name='id_camara',
        ),
    ]
