# Generated by Django 2.0.4 on 2018-05-13 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('politicos', '0006_remove_deputado_id_camara'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastocotaparlamentar',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos_deputados', to='empresas.Empresa'),
        ),
    ]
