# Generated by Django 2.0.4 on 2018-05-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicos', '0007_auto_20180513_0241'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gastocotaparlamentar',
            index=models.Index(fields=['-data_emissao'], name='politicos_g_data_em_147448_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocotaparlamentar',
            index=models.Index(fields=['data_emissao'], name='politicos_g_data_em_706148_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocotaparlamentar',
            index=models.Index(fields=['mes'], name='politicos_g_mes_2ed906_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocotaparlamentar',
            index=models.Index(fields=['ano'], name='politicos_g_ano_2863bc_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocotaparlamentar',
            index=models.Index(fields=['descricao'], name='politicos_g_descric_179e32_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocotaparlamentar',
            index=models.Index(fields=['descricao_especificacao'], name='politicos_g_descric_747dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocotaparlamentar',
            index=models.Index(fields=['fornecedor'], name='politicos_g_fornece_d50161_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocotaparlamentar',
            index=models.Index(fields=['valor_liquido'], name='politicos_g_valor_l_54a491_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocotaparlamentar',
            index=models.Index(fields=['valor_documento'], name='politicos_g_valor_d_77e5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocotaparlamentar',
            index=models.Index(fields=['deputado'], name='politicos_g_deputad_193b26_idx'),
        ),
        migrations.AddIndex(
            model_name='gastocotaparlamentar',
            index=models.Index(fields=['empresa'], name='politicos_g_empresa_edaff8_idx'),
        ),
    ]
