# Generated by Django 2.0.4 on 2018-05-04 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='unidade_federativa',
        ),
    ]
