# Generated by Django 2.0.4 on 2018-05-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_remove_empresa_unidade_federativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socio',
            name='empresa_origem',
        ),
        migrations.AddField(
            model_name='socio',
            name='cpf_cnpj_socio',
            field=models.CharField(db_index=True, max_length=14, null=True),
        ),
    ]
