# Generated by Django 2.0.4 on 2018-05-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='empresas',
            field=models.ManyToManyField(db_index=True, through='empresas.Sociedade', to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='estrangeiro',
            name='empresas',
            field=models.ManyToManyField(db_index=True, through='empresas.Sociedade', to='empresas.Empresa'),
        ),
        migrations.AlterField(
            model_name='pessoafisica',
            name='empresas',
            field=models.ManyToManyField(db_index=True, through='empresas.Sociedade', to='empresas.Empresa'),
        ),
    ]
